<a href="https://colab.research.google.com/github/2303A51688/ADM_Lab/blob/main/Lab_06(2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
import pandas as pd

In [6]:
df=pd.read_csv('/content/university_student.csv')

In [7]:
df

,Student ID,Gender,Date of Birth,Study Time,Grade,School Type,Absences,Math Score,Reading Score,Writing Score
0,1,Male,1996-12-03,11,D,Public,2,72,91,69
1,2,Female,2001-09-15,5,D,Private,0,66,58,62
2,3,Male,2002-08-09,8,A,Private,2,75,99,77
3,4,Male,1999-04-29,8,A,Private,3,57,76,97
4,5,Male,1995-06-11,9,B,Private,1,78,51,78
...,...,...,...,...,...,...,...,...,...,...
95,96,Female,2004-12-04,8,C,Public,1,87,85,88
96,97,Female,2003-01-18,7,B,Private,4,56,76,87
97,98,Female,1999-01-24,14,A,Private,2,95,66,83
98,99,Female,2005-04-20,7,B,Private,1,62,58,87
99,100,Male,2004-12-25,7,B,Private,2,89,82,99

In [9]:
df.isna()

,Student ID,Gender,Date of Birth,Study Time,Grade,School Type,Absences,Math Score,Reading Score,Writing Score
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
95,False,False,False,False,False,False,False,False,False,False
96,False,False,False,False,False,False,False,False,False,False
97,False,False,False,False,False,False,False,False,False,False
98,False,False,False,False,False,False,False,False,False,False
99,False,False,False,False,False,False,False,False,False,False

In [10]:
df.isna().sum()

Student ID       0
Gender           0
Date of Birth    0
Study Time       0
Grade            0
School Type      0
Absences         0
Math Score       0
Reading Score    0
Writing Score    0
dtype: int64

In [11]:
numeric_df = df.select_dtypes(include=['number'])

In [12]:
df_mean = numeric_df.mean()
print(df_mean)

Student ID       50.50
Study Time        9.81
Absences          2.50
Math Score       76.03
Reading Score    74.37
Writing Score    74.85
dtype: float64

In [13]:
df.fillna(df.mean(numeric_only=True), inplace=True)

In [16]:
df

,Student ID,Date of Birth,Study Time,Grade,Absences,Math Score,Reading Score,Writing Score,Gender_Male,School Type_Public
0,1,1996-12-03,11,D,2,72,91,69,True,True
1,2,2001-09-15,5,D,0,66,58,62,False,False
2,3,2002-08-09,8,A,2,75,99,77,True,False
3,4,1999-04-29,8,A,3,57,76,97,True,False
4,5,1995-06-11,9,B,1,78,51,78,True,False
...,...,...,...,...,...,...,...,...,...,...
95,96,2004-12-04,8,C,1,87,85,88,False,True
96,97,2003-01-18,7,B,4,56,76,87,False,False
97,98,1999-01-24,14,A,2,95,66,83,False,False
98,99,2005-04-20,7,B,1,62,58,87,False,False
99,100,2004-12-25,7,B,2,89,82,99,True,False

In [14]:
from sklearn.preprocessing import LabelEncoder
from datetime import datetime

In [15]:
df = pd.get_dummies(df, columns=["Gender", "School Type"], drop_first=True)

In [17]:
df

,Student ID,Date of Birth,Study Time,Grade,Absences,Math Score,Reading Score,Writing Score,Gender_Male,School Type_Public
0,1,1996-12-03,11,D,2,72,91,69,True,True
1,2,2001-09-15,5,D,0,66,58,62,False,False
2,3,2002-08-09,8,A,2,75,99,77,True,False
3,4,1999-04-29,8,A,3,57,76,97,True,False
4,5,1995-06-11,9,B,1,78,51,78,True,False
...,...,...,...,...,...,...,...,...,...,...
95,96,2004-12-04,8,C,1,87,85,88,False,True
96,97,2003-01-18,7,B,4,56,76,87,False,False
97,98,1999-01-24,14,A,2,95,66,83,False,False
98,99,2005-04-20,7,B,1,62,58,87,False,False
99,100,2004-12-25,7,B,2,89,82,99,True,False

In [18]:
df["Grade"] = LabelEncoder().fit_transform(df["Grade"])

In [19]:
df["Date of Birth"] = pd.to_datetime(df["Date of Birth"])
df["Age"] = datetime.now().year - df["Date of Birth"].dt.year
df["Total Score"] = df["Math Score"] + df["Reading Score"] + df["Writing Score"]

In [20]:
df.drop(columns=["Date of Birth"], inplace=True)

In [21]:
grouped_df = df.groupby("Grade").agg({
    "Total Score": "mean",
    "Age": "mean",
    "Absences": "sum"
}).reset_index()

In [22]:
print("\nTransformed Dataset:")
print(df.head())

print("\nGrouped and Aggregated Data:")
print(grouped_df)

Transformed Dataset:
   Student ID  Study Time  Grade  Absences  Math Score  Reading Score  \
0           1          11      3         2          72             91
1           2           5      3         0          66             58
2           3           8      0         2          75             99
3           4           8      0         3          57             76
4           5           9      1         1          78             51

   Writing Score  Gender_Male  School Type_Public  Age  Total Score
0             69         True                True   29          232
1             62        False               False   24          186
2             77         True               False   23          251
3             97         True               False   26          230
4             78         True               False   30          207

Grouped and Aggregated Data:
   Grade  Total Score        Age  Absences
0      0   232.535714  24.750000        80
1      1   215.500000  23.166667        30
2      2   230.428571  25.333333        50
3      3   227.304348  25.086957        52
4      4   210.062500  25.312500        38